trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      docker compose -f ./docker-compose/docker-compose.tests.yml up -d
      sleep 10
    displayName: 'docker compose -f ./docker-compose/docker-compose.tests.yml up -d'

  - task: UseDotNet@2
    displayName: 'install .net sdk 8.x'
    inputs:
      version: 8.x
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      $(Agent.ToolsDirectory)/dotnet/dotnet restore
    displayName: 'run restore (nuget)'

  - script: |
      $(Agent.ToolsDirectory)/dotnet/dotnet build --no-restore --verbosity d
    displayName: 'run build'

  - script: |
      $(Agent.ToolsDirectory)/dotnet/dotnet test --logger trx --results-directory $(Agent.TempDirectory) --verbosity d
    displayName: 'run tests'

  - task: PublishTestResults@2
    displayName: 'publish test results'
    inputs:
      testResultsFiles: '$(Agent.TempDirectory)/*.trx'
      testResultsFormat: VSTest
      publishRunAttachments: true