global using System;
global using System.Net;
global using FluentAssertions;
global using SalesPro.DTOs;
global using SalesPro.Entities;
global using SalesPro.Interfaces;
global using SalesPro.Tests.Environment;
global using SalesPro.Tests.TestEntities;
global using Xunit;